# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  ray-head:
    build:
      context: .
    command: ray start --temp-dir="/tmp/test_tmp" --head --port=6379 --dashboard-host=0.0.0.0 --block
    ports:
      - "6379:6379"
      - "8265:8265"
    environment:
      - RAY_ADDRESS=auto
    shm_size: "2G"

  ray-worker:
    build:
      context: .
    command: ray start --address=ray-head:6379 --block
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Maximum 1 CPU core
          memory: "2G"
    depends_on:
      - ray-head
    shm_size: "2G"

